version = 0.1
[default.deploy.parameters]
stack_name = "adeel"
resolve_s3 = true
s3_prefix = "adeel"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
